#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for the Intel network device drivers.
#
#
#obj-$(CPTCFG_E100) += e100.o
#obj-$(CPTCFG_E1000) += e1000/
#obj-$(CPTCFG_E1000E) += e1000e/
obj-$(CPTCFG_IGB) += igb/
#obj-$(CPTCFG_IGBVF) += igbvf/
#obj-$(CPTCFG_IXGBE) += ixgbe/
#obj-$(CPTCFG_IXGBEVF) += ixgbevf/
#obj-$(CPTCFG_I40E) += i40e/
#obj-$(CPTCFG_IXGB) += ixgb/
#obj-$(CPTCFG_I40EVF) += i40evf/
