#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for the Broadcom network device drivers.
#

obj-$(CPTCFG_B44) += b44.o
#obj-$(CPTCFG_BCM63XX_ENET) += bcm63xx_enet.o
#obj-$(CPTCFG_BCMGENET) += genet/
#obj-$(CPTCFG_BNX2) += bnx2.o
#obj-$(CPTCFG_CNIC) += cnic.o
#obj-$(CPTCFG_BNX2X) += bnx2x/
#obj-$(CPTCFG_SB1250_MAC) += sb1250-mac.o
#obj-$(CPTCFG_TIGON3) += tg3.o
#obj-$(CPTCFG_BGMAC) += bgmac.o
#obj-$(CPTCFG_SYSTEMPORT) += bcmsysport.o
