/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Tue Mar 01 18:07:40 2016
 * Do Not Modify the File.
 */



#include "pmic_drv.h"





















//For PMIC driver use
void pmic_init(void) {
}



