#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Makefile for the LDVT drivers for UVVTP

obj-y   += vdec/
obj-y   += UDVT/
#obj-$(CONFIG_MTK_LDVT_PMIC)   += pmic/
#obj-$(CONFIG_MTK_LDVT_PMIC_WARP)   += pmic_wrap/
obj-y   += hotplug/
#obj-y   += pwm/
#obj-y   += adc/
#obj-y   += mhltx/
#obj-y   += hdmitx/
