#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# drivers/image/jpeg/Makefile

EXTRA_CFLAGS = -DSDEBUG_T

#ccflags-y += -I$(MTK_PATH_SOURCE)/drivers/jpeg/

#obj-$(CONFIG_MTK_JPEG) += jpeg_driver.o
obj-y += jpeg_driver.o

jpeg_driver-objs := jpeg_drv_6589_enc.o jpeg_drv_6589_dec.o jpeg_drv.o

#jpeg_driver-objs := jpeg_drv_6589_enc.o  jpeg_drv.o

# EOF
