#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Makefile for the linux kernel.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += vdec_hal_if_common.o
obj-y += vdec_hw_common.o
obj-y += vdec_hal_if_avs.o
obj-y += vdec_hal_if_h264.o
obj-y += vdec_hal_if_h265.o
obj-y += vdec_hal_if_mpeg.o
obj-y += vdec_hal_if_rm.o
obj-y += vdec_hal_if_vp6.o
obj-y += vdec_hal_if_vp8.o
obj-y += vdec_hal_if_vp9.o
obj-y += vdec_hal_if_wmv.o
# obj-y += vdec_hal_slt_rm.o
obj-y += vdec_hw_avs.o
obj-y += vdec_hw_h264.o
obj-y += vdec_hw_h265.o
obj-y += vdec_hw_mpeg.o
obj-y += vdec_hw_rm.o
obj-y += vdec_hw_vp6.o
obj-y += vdec_hw_vp8.o
obj-y += vdec_hw_vp9.o
