#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# MTK Platform Support
obj-$(CONFIG_SND_SOC_MT8135) += mt8135/
obj-$(CONFIG_SND_SOC_MT6595) += mt6595/
obj-$(CONFIG_SND_SOC_MT8127) += mt8127/
obj-$(CONFIG_SND_SOC_MT8590) += mt8590/
