#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
obj-$(CPTCFG_IEEE802154_FAKEHARD) += fakehard.o
obj-$(CPTCFG_IEEE802154_FAKELB) += fakelb.o
obj-$(CPTCFG_IEEE802154_AT86RF230) += at86rf230.o
obj-$(CPTCFG_IEEE802154_MRF24J40) += mrf24j40.o
obj-$(CPTCFG_IEEE802154_CC2520) += cc2520.o
