/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 09 15:28:26 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


