#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
obj-$(CPTCFG_SOC_CAMERA_IMX074)		+= imx074.o
obj-$(CPTCFG_SOC_CAMERA_MT9M001)	+= mt9m001.o
obj-$(CPTCFG_SOC_CAMERA_MT9M111)	+= mt9m111.o
obj-$(CPTCFG_SOC_CAMERA_MT9T031)	+= mt9t031.o
obj-$(CPTCFG_SOC_CAMERA_MT9T112)	+= mt9t112.o
obj-$(CPTCFG_SOC_CAMERA_MT9V022)	+= mt9v022.o
obj-$(CPTCFG_SOC_CAMERA_OV2640)		+= ov2640.o
obj-$(CPTCFG_SOC_CAMERA_OV5642)		+= ov5642.o
obj-$(CPTCFG_SOC_CAMERA_OV6650)		+= ov6650.o
obj-$(CPTCFG_SOC_CAMERA_OV772X)		+= ov772x.o
obj-$(CPTCFG_SOC_CAMERA_OV9640)		+= ov9640.o
obj-$(CPTCFG_SOC_CAMERA_OV9740)		+= ov9740.o
obj-$(CPTCFG_SOC_CAMERA_RJ54N1)		+= rj54n1cb0c.o
obj-$(CPTCFG_SOC_CAMERA_TW9910)		+= tw9910.o
