# drivers/video/mtk/Makefile
#
# Makefile for MT8590 video driver.
#

ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/dgi/  \
             -I$(MTK_PATH_SOURCE)/drivers/dgi/    \
             -I$(MTK_PATH_PLATFORM)/drivers/dgi/  \
             -I$(MTK_PATH_SOURCE)/drivers/dgi/    \
             -I$(srctree)/drivers/misc/mediatek/hdmirx/$(CONFIG_MTK_PLATFORM)   \
             -I$(srctree)/drivers/misc/mediatek/videoin/$(CONFIG_MTK_PLATFORM)   \
             -I$(srctree)/drivers/misc/mediatek/videoif/$(CONFIG_MTK_PLATFORM)   \
             
obj-y	:= dgi_if.o dgi_hal.o 




