#
# Makefile for icx_cradle (wmport driver).


ccflags-y += -I$(srctree)/drivers/misc/mediatek/uart/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/auxadc/

obj-$(CONFIG_ENABLE_WMPORT)		+= icx_cradle.o
