#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for USB Class drivers
# (one step up from the misc category)
#
#
#obj-$(CPTCFG_USB_ACM)		+= cdc-acm.o
#obj-$(CPTCFG_USB_PRINTER)	+= usblp.o
obj-$(CPTCFG_USB_WDM)		+= cdc-wdm.o
#obj-$(CPTCFG_USB_TMC)		+= usbtmc.o
