/*
 * Copyright 2016 Sony Corporation
 * File changed on 2016-01-20
 */
/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 01 16:32:34 2016
 * Do Not Modify the File.
 */



#include <mach/upmu_sw.h>


//****for customer use*******// 


//PMIC default enable/disable result

//PMIC mode select 
typedef enum
{
   BY_ENABLE = 0,
   BY_SRCLKEN = 1
}MODE_sel_enum;

////For Common use 

//For PMIC driver use
void pmic_init(void);




