#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
EXTRA_CFLAGS += -D_USB_NORMAL_

obj-y := mu3d_hal.o

mu3d_hal-y := mu3d_hal_osal.o \
              mu3d_hal_qmu_drv.o \
              mu3d_hal_usb_drv.o \
              mu3d_hal_phy.o \
              mu3d_hal_comm.o
