#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
zr36067-objs	:=	zoran_procfs.o zoran_device.o \
			zoran_driver.o zoran_card.o

obj-$(CPTCFG_VIDEO_ZORAN) += zr36067.o videocodec.o
obj-$(CPTCFG_VIDEO_ZORAN_DC30) += zr36050.o zr36016.o
obj-$(CPTCFG_VIDEO_ZORAN_ZR36060) += zr36060.o
