#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for radios with Silicon Labs Si470x FM Radio Receivers
#

radio-usb-si470x-objs	:= radio-si470x-usb.o radio-si470x-common.o
radio-i2c-si470x-objs	:= radio-si470x-i2c.o radio-si470x-common.o

obj-$(CPTCFG_USB_SI470X) += radio-usb-si470x.o
obj-$(CPTCFG_I2C_SI470X) += radio-i2c-si470x.o
