#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_TOUCHPANEL)	+=  gt1x_extents.o
obj-$(CONFIG_MTK_TOUCHPANEL)	+=  gt1x_generic.o
obj-$(CONFIG_MTK_TOUCHPANEL)	+=  gt1x_tools.o
obj-$(CONFIG_MTK_TOUCHPANEL)	+=  gt1x_tpd.o
obj-$(CONFIG_MTK_TOUCHPANEL)	+=  gt1x_update.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  mtk_tpd.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_button.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_calibrate.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_debug.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_default.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_init.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_misc.o
obj-$(CONFIG_MTK_TOUCHPANEL)   +=  tpd_setting.o

obj-$(CONFIG_TOUCHSCREEN_ICX)	+= icx_ts_i2c_devs.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_ICX)	+= icx_synaptics_i2c_devs.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX8526_ICX)	+= icx_himax_hx8526_i2c_devs.o
