#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Makefile for the power golden setting.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += mt_power_gs.o
obj-y += mt_power_gs_array.o
obj-y += mt_power_gs_suspend.o
obj-y += mt_power_gs_2g_paging.o
obj-y += mt_power_gs_3g_paging.o
obj-y += mt_power_gs_tdd_paging.o
obj-y += mt_power_gs_2g_talking.o
obj-y += mt_power_gs_3g_talking.o
obj-y += mt_power_gs_tdd_talking.o
obj-y += mt_power_gs_data_connection.o
obj-y += mt_power_gs_connsys.o
obj-y += mt_power_gs_dpidle.o
obj-y += mt_power_gs_idle.o
obj-y += mt_power_gs_audio_playback.o
obj-y += mt_power_gs_video_record.o
