#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for the Intel Centrino wireless drivers
#

obj-$(CPTCFG_IPW2100) += ipw2100.o
obj-$(CPTCFG_IPW2200) += ipw2200.o

obj-$(CPTCFG_LIBIPW) += libipw.o
libipw-objs := \
	libipw_module.o \
	libipw_tx.o \
	libipw_rx.o \
	libipw_wx.o \
	libipw_geo.o
