/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Fri Jan 30 16:54:06 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


