#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for ST21NFCA HCI based NFC driver
#

st21nfca_hci-objs = st21nfca.o st21nfca_dep.o
obj-$(CPTCFG_NFC_ST21NFCA)     += st21nfca_hci.o

st21nfca_i2c-objs  = i2c.o
obj-$(CPTCFG_NFC_ST21NFCA_I2C) += st21nfca_i2c.o
