/*
 * Copyright 2016 Sony Corporation
 * File changed on 2016-01-20
 */
/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Tue May 10 18:50:49 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_EINTH
#define __CUST_EINTH
#ifdef __cplusplus
extern "C" {
#endif
#define CUST_EINTF_TRIGGER_RISING     			1    //High Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_FALLING    			2    //Low Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_HIGH      				4    //High Polarity and Level Sensitive
#define CUST_EINTF_TRIGGER_LOW       				8    //Low Polarity and Level Sensitive
#define CUST_EINT_DEBOUNCE_DISABLE          0
#define CUST_EINT_DEBOUNCE_ENABLE           1
//////////////////////////////////////////////////////////////////////////////


#define CUST_EINT_IRQ_SONY_DMP_NFC_NUM              28
#define CUST_EINT_IRQ_SONY_DMP_NFC_DEBOUNCE_CN      0
#define CUST_EINT_IRQ_SONY_DMP_NFC_TYPE							CUST_EINTF_TRIGGER_FALLING
#define CUST_EINT_IRQ_SONY_DMP_NFC_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_MSDC1_INS_NUM              74
#define CUST_EINT_MSDC1_INS_DEBOUNCE_CN      1
#define CUST_EINT_MSDC1_INS_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_MSDC1_INS_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_USB_VBUS_NUM              89
#define CUST_EINT_USB_VBUS_DEBOUNCE_CN      0
#define CUST_EINT_USB_VBUS_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_USB_VBUS_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_USB_IDDIG_NUM              122
#define CUST_EINT_USB_IDDIG_DEBOUNCE_CN      0
#define CUST_EINT_USB_IDDIG_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_USB_IDDIG_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE



//////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
}
#endif
#endif //_CUST_EINT_H


