/*
 * Copyright 2016 Sony Corporation
 * File changed on 2016-01-20
 */
/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8590. Copyright MediaTek Inc. (C) 2013.
 * Mon Jan 19 15:52:34 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


