#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for the ir drivers.
#
        
#obj-m += ir.o 
#ir-objs := mtk_ir_core.o mtk_ir_nec.o mtk_ir_rc6.o mtk_ir_rc5.o mtk_ir_dev.o mtk_ir_netlink.o mtk_ir_mouse.o


obj-y := mtk_ir_core.o mtk_ir_nec.o mtk_ir_rc6.o mtk_ir_rc5.o mtk_ir_sirc.o mtk_ir_rstep.o mtk_ir_dev.o mtk_ir_netlink.o mtk_ir_mouse.o 

