#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
#
# Makefile for the kernel multimedia device drivers.
#

obj-y        +=	ttpci/		\
		b2c2/		\
		pluto2/		\
		dm1105/		\
		pt1/		\
		mantis/		\
		ngene/		\
		ddbridge/	\
		b2c2/		\
		saa7146/

obj-$(CPTCFG_VIDEO_IVTV) += ivtv/
obj-$(CPTCFG_VIDEO_ZORAN) += zoran/
obj-$(CPTCFG_VIDEO_CX18) += cx18/
obj-$(CPTCFG_VIDEO_CX23885) += cx23885/
obj-$(CPTCFG_VIDEO_CX25821) += cx25821/
obj-$(CPTCFG_VIDEO_CX88) += cx88/
obj-$(CPTCFG_VIDEO_BT848) += bt8xx/
obj-$(CPTCFG_VIDEO_SAA7134) += saa7134/
obj-$(CPTCFG_VIDEO_SAA7164) += saa7164/
obj-$(CPTCFG_VIDEO_MEYE) += meye/
obj-$(CPTCFG_STA2X11_VIP) += sta2x11/
obj-$(CPTCFG_VIDEO_SOLO6X10) += solo6x10/
