#
# Copyright (C) 2011-2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Makefile for the linux kernel.

obj-y := UDVT.o
obj-y   += UDVT_cmd.o
obj-y   += UDVT_IF.o
obj-y   += UDVT_fs_linux.o
obj-y   += os_linux_util.o
obj-y   += os_init.o
obj-y   += os_linux_crit.o
obj-y   += os_linux_ev_grp.o
obj-y   += os_linux_mem.o
obj-y   += os_linux_msg_q.o
obj-y   += os_linux_sema.o
obj-y   += os_linux_thread.o
obj-y   += os_linux_timer.o
